[project]
name = "isession"
version = "0.1.0"
description = "A pre-configured iPython session."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipython>=9.0.1",
    "exif>=1.6.1",
    "ipython>=8.33.0",
    "piexif>=1.1.3",
    "pillow>=11.1.0",
    "tqdm>=4.67.1",
]
